Feat/macrocommand
smnk-1/OOPnD pull request #35
Opened 2024-12-18 06:47 UTC by Kreoniz

10. Определить команду MacroCommand для выполнения последовательности команд.

MacroCommand в конструктор получает массив ICommand. Метод Execute последовательно выполняет все команды из массива.

Критерии приемки:

1.     Для реализации MacroCommand не используются циклы.
2.     Реализован тест "MacroCommand выполняет все команды из массива".
3.     Реализован тест, который проверяет, что MacroCommand.Execute выбрасывает исключение, если одна из команд выбрасывает исключение, оставшиеся команды не выполняются.

2024-12-24 11:23 UTC, zaryanezrya commented
Низкое покрытие

2024-12-24 11:41 UTC, zaryanezrya requested changes
Сначала решил скидывать по одному замечания после того, как увидел маленькое покрытие. Но после того, как увидел код, решил, что это затянется. Вот пачка замечаний, которые сразу бросились в глаза.

До содержательной проверки, как видите, ещё дойти не удалось, много помарок.

2024-12-24 11:41 UTC, zaryanezrya commented on StarWars.Lib/MacroCommand.cs
> +        commandList = cmds.ToList<ICommand>();
Здесь нет необходимости в разделении на обявление и присваивание.
Создаётся лишний объект в памяти, который не используется.

2024-12-24 11:41 UTC, zaryanezrya commented on StarWars.Lib/MacroCommand.cs
> +    public MacroCommand(params ICommand[] commands)
Передаётся IEnumerable<ICommand>,  без params

2024-12-24 11:41 UTC, zaryanezrya commented on StarWars.Lib/MacroCommandIoC.cs
> +            (object[] args) => (StarWars.Lib.ICommand)new MacroCommand(args.Select(x => (StarWars.Lib.ICommand)x).ToArray())).Execute();
Много возни с интерфейсом ICommand. Оставьте только один из IoC

2024-12-24 11:41 UTC, zaryanezrya commented on StarWars.Lib/MacroCommandIoC.cs
> +            (object[] args) => (StarWars.Lib.ICommand)new MacroCommand(args.Select(x => (StarWars.Lib.ICommand)x).ToArray())).Execute();
Усложнение передачи параметров из-за params

2024-12-24 11:41 UTC, zaryanezrya commented on StarWars.Tests/CreateMacroCommandStrategyTests.cs
> +            IoC.Resolve<Hwdtech.ICommand>("Scopes.Current.Set", iocScope).Execute();
А это почему в конструктор не вынесли?

2024-12-24 11:41 UTC, zaryanezrya commented on StarWars.Tests/CreateMacroCommandStrategyTests.cs
> +                "Specs.Macro.Test",
Должно быть Specs.Test

2024-12-24 11:41 UTC, zaryanezrya commented on StarWars.Tests/CreateMacroCommandStrategyTests.cs
> +            var strategy = new CreateMacroCommandStrategy("Macro.Test");
Должно быть Test, а не Macro.Test

2024-12-24 11:41 UTC, zaryanezrya commented on StarWars.Lib/CreateMacroCommandStrategy.cs
> +            Console.WriteLine($"Received {args.Length} arguments.");
Console.WriteLine ... T_T

2024-12-24 11:41 UTC, zaryanezrya commented on StarWars.Lib/CreateMacroCommandStrategy.cs
> +        if (IoC.Resolve<object>("Specs." + commandSpec) is not string[] commandNames)
Лишняя проверка, и так будет выброшено исключение, что не найдена такая зависимость

2024-12-24 11:41 UTC, zaryanezrya commented on StarWars.Lib/CreateMacroCommandStrategy.cs
> +        if (!commands.Any())
Почему не может быть команд, где пустые спеки? Лишняя проверка.

2024-12-25 18:18 UTC, osm1us requested changes
...

2024-12-25 18:18 UTC, osm1us commented on StarWars.Tests/ActionStopIoCTests.cs
Нет инициализации скоупа, чревато тем, что в будущем тесты будут работать с переменным успехом

            IoC.Resolve<ICommand>("Scopes.Current.Set",
            IoC.Resolve<object>("Scopes.New", IoC.Resolve<object>("Scopes.Root"))).Execute();

2024-12-25 18:18 UTC, osm1us commented on StarWars.Tests/MacroCommandIoCTests.cs
Повтор замечания про скоупы

2024-12-25 19:19 UTC, smnk-1 commented on StarWars.Tests/MacroCommandIoCTests.cs
fixed

2024-12-25 19:19 UTC, smnk-1 commented on StarWars.Tests/ActionStopIoCTests.cs
fixed

2024-12-25 20:04 UTC, zaryanezrya requested changes
Нет реализации начала и остановки

2024-12-25 20:04 UTC, zaryanezrya commented on StarWars.Lib/CreateMacroCommandStrategy.cs
> +        var commands = commandNames.Select(name => IoC.Resolve<Hwdtech.ICommand>(name)).ToArray();
При конструировании команд передаётся объект. Для него команда конструируется. Для этого и нужны параметры у этого метода

2024-12-26 02:34 UTC, Kreoniz commented on .editorconfig
> +dotnet_diagnostic.IDE0060.severity = silent
отваливается dotnet format --verify-no-changes в resolve(args)

2024-12-26 04:42 UTC, Kreoniz commented on StarWars.Lib/CreateMacroCommandStrategy.cs
> +        var commands = commandNames.Select(name => IoC.Resolve<Hwdtech.ICommand>(name)).ToArray();
> При конструировании команд передаётся объект. Для него команда конструируется. Для этого и нужны параметры у этого метода

?

2024-12-26 09:59 UTC, osm1us reviewed
Вроде ок, а вроде и не ок

2024-12-26 09:59 UTC, osm1us commented on StarWars.Lib/MacroCommand.cs
> +        var commandList = cmds.ToList();
Лишний обьект в памяти, можно без него

2025-01-25 12:38 UTC, zaryanezrya approved these changes

2025-02-24 05:33 UTC, merged