added InjectableClass and InjectableTest
smnk-1/OOPnD pull request #37
Opened 2024-12-18 16:00 UTC by rabigede

16. Определить интерфейс ICommandInjectable
public interface ICommandInjectable { void Inject(ICommand command); }

17. Определить команду CommandInjectableCommand
Команда реализует два интерфейса ICommand и ICommandIjectable.
Критерии приемки:
Реализован тест, который проверяет, что после того как команда будет внедрена в объект класса CommandInjectableCommand, то она будет вызвана при выполнении метода Execute объекта класса CommandInjectableCommand.
Реализован тест, который проверяет, что вызов Execute класса CommandInjectableCommand выбрасывает исключение, если не была внедерена команда.

Выполнил Макеев Всеволод ФИТ-232

2024-12-24 12:09 UTC, zaryanezrya requested changes
Не увидел 18 задачи

2024-12-24 12:11 UTC, zaryanezrya commented
Смотрел список задач по issue.

2024-12-25 16:44 UTC, KryakPingvi approved these changes
переделать интерфейс и его реализацию

2024-12-25 16:44 UTC, KryakPingvi commented on StarWars.Lib/InjectableClass.cs
> +public interface ICommandInjectable
из вики:
16. Определить интерфейс ICommandInjectable
public interface ICommandInjectable
{
    void Inject(ICommand command);
}

2024-12-25 16:44 UTC, KryakPingvi commented on StarWars.Lib/InjectableCommandIoc.cs
> +﻿using Hwdtech;
Hwdtech перед ICommand

2024-12-25 17:08 UTC, zaryanezrya requested changes

2024-12-25 17:08 UTC, zaryanezrya commented on StarWars.Lib/InjectableClass.cs
> +    void Execute();
Да, это лишнее

2024-12-25 21:27 UTC, zaryanezrya approved these changes

2024-12-26 02:41 UTC, merged